### ISSUE TITLE
Segmentation fault on raspbian buster armv61

### ISSUE THREAD

**Issue by dkgs** [Gulden/gulden-official#168]
Hello, I've wanted to move my gulden node from my pine64 which is overloaded to a Raspberry Pi Model B Rev 2.

This rpi will be totally dedicated to the Gulden node with G-dash.
I installed a fresh raspbian buster minimal image and updated the firmware & hardware.

As there is no gulden repo available for buster, I pointed to the stretch. (I followed steps as described in https://g-dash.nl/?page=download).

When trying to just get the available options for GuldenD or Gulden-cli with the "-h" option I directly get a Segmentation fault.

Then, I downloaded directly the linux-arm-eabihf version from the release section on this github, same problem.

I checked ulimit => unlimited

### Machine specs:
- OS: Raspbian GNU/Linux 10 (buster)
- CPU: ARMv6-compatible processor rev7 (v61)
- RAM: 512Mo
- Disk size: 8Gb
- Disk Type (HD/SDD): f2fs flash drive

### Any extra information that might be useful in the debugging process.
I tried to gdb the exec, but as there is no debug info in the exec, i just get some odd addresses.
I tried to compile gulden directly on the pi, nearly killed it when compiling boost...

I would be happy to follow some hints if you've got some :)

**Comment by mjmacleod** [comment]
A few things you can do for starters to rule out the obvious:

1) Make sure you are running the hard float version of raspbian buster and not the soft float version
2) Check the output of dmesg after the segfault if there are any clues there.

Assuming neither of those two help I can upload the split-debug symbols, which you can hopefully use for a stack trace during the course of tomorrow when I have access to the build server where they are stored.

**Comment by dkgs** [comment]
1. Hard float checked:
I got the /lib/arm-linux-gnueabihf folder

```
$ dpkg -l | grep eabi
ii  binutils-arm-linux-gnueabihf   2.31.1-16+rpi1              armhf        GNU binary utilities, for arm-linux-gnueabihf target
```

2. dmesg doesn't show me anything I think related:
```
$ dmesg | tail
[   70.404068] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   70.501529] bcm2835_audio soc:audio: card created with 8 channels
[   71.816172] usbcore: registered new interface driver uas
[   72.688882] sd 0:0:0:0: Attached scsi generic sg0 type 0
[   81.620658] 8021q: 802.1Q VLAN Support v1.8
[   82.310684] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   82.850293] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   83.784130] Adding 102396k swap on /var/swap.  Priority:-2 extents:52 across:2089864k FS
[   83.829105] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   85.249528] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xDDE1
```

Ok, if you have a debug version, I'll happily give you the stack trace.

**Comment by mjmacleod** [comment]
Sorry it appears the build server is broken, so there will be a bit of a delay before I can get you the debug symbols from it.

In the meantime the other obvious thing is memory. Please ensure you have adequate swap enabled (ideally 4gb or so) and see if that helps.

**Comment by dkgs** [comment]
Swap could have been the problem as the rpi has only 100Mo of swap by default. Hence, I added a dedicated 4Go usb to check (just for the purpose of the test, otherwise the risk is that i will not live that long).

I then got the following swap available :
```
 $ sudo swapon -s
Filename                                Type            Size    Used    Priority
/dev/sdb1                               partition       3956704 520     -2
/var/swap                               file            102396  0       -3
```

Still got the segmentation fault :(

**Comment by mjmacleod** [comment]
https://github.com/Gulden/gulden-official/releases/tag/v2.1.0.5_1|

Extract both the debug symbols and binaries side by side and then you should be able to get a meaningful stack track.

`thread apply all backtrace` in gdb after the crash to get a backtrace for all threads.

**Comment by dkgs** [comment]
Ok, here is what I get along with the following commands :

```
$ wget https://github.com/Gulden/gulden-official/releases/download/v2.1.0.5_1/Gulden-2.1.0-arm-linux-gnueabihf-debug.tar.gz
[...]
$ wget https://github.com/Gulden/gulden-official/releases/download/v2.1.0.5_1/Gulden-2.1.0-arm-linux-gnueabihf.tar.gz
[...]
$ tar xvf Gulden-2.1.0-arm-linux-gnueabihf
[...]
$ tar xvf Gulden-2.1.0-arm-linux-gnueabihf-debug.tar.gz
[...]
$ cd Gulden-2.1.0/
$ gdb bin/GuldenD                                                                        
GNU gdb (Raspbian 8.2.1-2) 8.2.1                                                                                                      
Copyright (C) 2018 Free Software Foundation, Inc.                                                                                     
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                                         
This is free software: you are free to change and redistribute it.                                                                    
There is NO WARRANTY, to the extent permitted by law.                                                                                 
Type "show copying" and "show warranty" for details.                                                                                  
This GDB was configured as "arm-linux-gnueabihf".                                                                                     
Type "show configuration" for configuration details.                                                                                  
For bug reporting instructions, please see:                                                                                           
<http://www.gnu.org/software/gdb/bugs/>.                                                                                              
Find the GDB manual and other documentation resources online at:                                                                      
    <http://www.gnu.org/software/gdb/documentation/>.                                                                                 
                                                                                                                                      
For help, type "help".                                                                                                                
Type "apropos word" to search for commands related to "word"...                                                                       
Reading symbols from bin/GuldenD...Reading symbols from /opt/gulden/test/Gulden-2.1.0/bin/GuldenD.dbg...done.                         
done.                                                                                                                                 
(gdb) run -h                                                                                                                          
Starting program: /opt/gulden/test/Gulden-2.1.0/bin/GuldenD -h                                                                        
[Thread debugging using libthread_db enabled]                                                                                         
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".                                                         
                                                                                                                                      
Program received signal SIGSEGV, Segmentation fault.                                                                                  
0x004a4e9c in boost::detail::interruption_checker::unlock_if_locked (this=0xbefff69c)                                                 
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/thread_data.hpp:221                
221     /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/thread_data.hpp: No such file or d
irectory.                                                                                                                             
(gdb) thread apply all backtrace                                                                                                      
                                                                                                                                      
Thread 1 (Thread 0xb6ff0010 (LWP 12450)):                                                                                             
#0  0x004a4e9c in boost::detail::interruption_checker::unlock_if_locked (this=0xbefff69c)                                             
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/thread_data.hpp:221                
#1  boost::detail::interruption_checker::unlock_if_locked (this=0xbefff69c)                                                           
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/thread_data.hpp:216                
#2  boost::condition_variable::wait (m=..., this=0x78)                                                                                
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/condition_variable.hpp:82          
#3  boost::shared_mutex::lock (this=0xbefff7a8)                                                                                       
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/shared_mutex.hpp:293               
#4  boost::lock_guard<boost::shared_mutex>::lock_guard (m_=..., this=<synthetic pointer>)                                             
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/lock_guard.hpp:38                          
#5  boost::thread_group::create_thread<boost::_bi::bind_t<void, void (*)(char const*, void (*)()), boost::_bi::list2<boost::_bi::value
<char const*>, boost::_bi::value<void (*)()> > > > (threadfunc=..., this=0x0)                                                         
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/detail/thread_group.hpp:78                 
#6  StartPoW2WitnessThread (threadGroup=...) at generation/witness.cpp:668                                                            
#7  0x6344b1aa in ?? ()                                                                                                               
Backtrace stopped: previous frame identical to this frame (corrupt stack?)      
```

Error on thread creation... doesn't look good, bug related to boost impl ?

**Comment by mjmacleod** [comment]
Hrm, thanks, it does indeed not look great, though it could be a red herring if there is other stack corruption involved.

1) Can you try run it with -disablewallet flag?
2) Also for curiosity what is the output of 'cat /proc/sys/kernel/threads-max'?
3) And finally, can you share the output of 'ldd GuldenD'?

**Comment by dkgs** [comment]
1. With -disablewallet, same problem :
```
$ ./bin/GuldenD -disablewallet
Segmentation fault
```
The problem is the same, just not the same trigger:
```
(gdb) run -disablewallet -h                                                                                                           
Starting program: /opt/gulden/test/Gulden-2.1.0/bin/GuldenD -disablewallet -h                                                         
[Thread debugging using libthread_db enabled]                                                                                         
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".                                                         
                                                                                                                                      
Program received signal SIGSEGV, Segmentation fault.                                                                                  
0x004a4e9c in boost::detail::interruption_checker::unlock_if_locked (this=0xbefff68c)                                                 
    at /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/thread_data.hpp:221                
221     /home/ubuntu/build/Gulden/depends/arm-linux-gnueabihf/share/../include/boost/thread/pthread/thread_data.hpp: No such file or d
irectory.
```

2. Max threads:
```
$ cat /proc/sys/kernel/threads-max
7549
```

3. ldd gives me that:
```
$ ldd ./bin/GuldenD                                                                      
        /usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v6l.so (0xb63dc000)           
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb63b2000)                                                      
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb639b000)                                                                
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6319000)                                                                  
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb62ec000)                                                          
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb619e000)                                                                  
        /lib/ld-linux-armhf.so.3 (0xb6eff000)
```
Is it possible to update the boost dependency actually 1.66 to the recent version 1.70, even though it doesn't seem to have any bug fix related to this problem in the boost changelog ?

**Comment by mjmacleod** [comment]
https://github.com/Gulden/gulden-official/releases/edit/v2.1.0.5_1 < new build against boost 1.70

This is a pi4b or a pi3b?

**Comment by dkgs** [comment]
With this new version i get another error:
```
(gdb) thread apply all backtrace                                                                                                      
                                                                                                                                      
Thread 1 (Thread 0xb6ff0010 (LWP 19336)):                                                                                             
#0  0x004a0860 in CReserveKeyOrScript::scriptOnly (this=this@entry=0x0) at generation/witness.cpp:83                                  
#1  0x00652912 in CReserveKeyOrScript::ReturnKey (this=this@entry=0x0) at wallet/wallet.cpp:2213                                      
#2  0x0049fd3c in CReserveKeyOrScript::~CReserveKeyOrScript (this=0x0, __in_chrg=<optimized out>) at generation/witness.cpp:79        
#3  0x00000000 in ?? ()                                                                                                               
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

It is a model B first of its name, hence should I tell pi1b ? It's not supported ?

**Comment by dkgs** [comment]
Wow, following an [old post about corrupted stack](https://www.raspberrypi.org/forums/viewtopic.php?t=60540) on raspberrypi, i tried to install lib6-dbg, i got:
```
$ sudo apt-get install libc6-dbg                                                                                     
E: Error reading the CPU table
```
My filesystem seems to be corrupted:
```
$ ll /usr/share/
ls: reading directory '/usr/share/': Invalid argument                                                                                 
total 0
```
Hence, I can't garantee any behaviour...

Until I replace the flash disk by a real hard drive or ssd, I can't pursue the investigation.
Don't know if the intial problem was due to the same problem...
I don't have physical access to the card right now.
You can suspend this issue, sorry for bothering you.

**Comment by mjmacleod** [comment]
Did a test this side and I get the same segfaults on a pi1b+ here - it appears that our toolchain uses various optimisations etc. that are present only on pi2 and upwards.

Theoretically it is possible to compile and run on pi1 but I'm not sure whether performance is really adequate enough to make it worthwhile, so I'm not sure if its something we want to support or not.
